# Generated by Django 3.0.7 on 2020-07-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('detail', models.CharField(max_length=255, unique=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'UN_DONE'), (1, 'IN_PROGRESS'), (2, 'COMPLETED')], default=0)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.Project')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
